# chunks will have a set size of 12 x 12
CHUNK_WIDTH = CHUNK_HEIGHT = 12
CHUNK_TILE_WIDTH = CHUNK_TILE_HEIGHT = 64
CHUNK_WIDTH_PIX = CHUNK_WIDTH * CHUNK_TILE_WIDTH
CHUNK_HEIGHT_PIX = CHUNK_HEIGHT * CHUNK_TILE_HEIGHT
CHUNK_TILE_AREA = (CHUNK_TILE_WIDTH, CHUNK_TILE_HEIGHT)

TILE_X = 0
TILE_Y = 1
TILE_IMG = 2
TILE_COL = 3



# serialization
CHUNK_TILEMAP_KEY = "tile"
CHUNK_POS_KEY = "pos"
CHUNK_IMAGES_KEY = "images"

ANIMATION_PATH_KEY = "a_path"
ANIMATION_NAME_KEY = "a_name"

RECT_X_KEY = "x"
RECT_Y_KEY = "y"
RECT_W_KEY = "w"
RECT_H_KEY = "h"

TILE_DATA_FRICTION_KEY = "friction"
# TBD
TILE_DATA_OTHER_JKEY = "other"

TILE_X_KEY = "x"
TILE_Y_KEY = "y"
TILE_IMG_KEY = "img"
TILE_COL_KEY = "col"
TILE_STATS_KEY = "stats"

ENTITY_RECT_KEY = "rect"
ENTITY_ANIMATION_KEY = "animation"
ENTITY_TYPE_KEY = "type"

SPRITETILE_INDEX_KEY = "index"
SPRITETILE_RECT_KEY = "rect"
SPRITETILE_PARENT_IMAGE_KEY = "parent_str"

SPRITESHEET_IMAGE_PATH_KEY = "s_path"
SPRITESHEET_SPRITES_KEY = "s_tiles"
SPRITESHEET_SPRITE_AREA_KEY = "s_area"
SPRITESHEET_SPACING_KEY = "s_spacing"

HANDLER_DATA_KEY = "entities"
HANDLER_ANIMATION_KEY = "animation"

WORLD_DATA_KEY = "world"
WORLD_CHUNK_KEY = "chunks"
WORLD_RENDER_DISTANCE_KEY = "r_dist"
WORLD_GRAVITY_KEY = "gravity"

STATE_HANDLER_KEY = "handler"
STATE_WORLD_KEY = "world"
STATE_GRAPHICS_KEY  = "graphics"

GRAPHICS_IMAGE_KEY = "images"
GRAPHICS_ANIMATION_KEY = "animations"



# world rendering

SPRITE_OBJECT_PREFIX = "spr_o_"

SPRITE_OBJECT_KEY = "sprite"
SPRITE_OBJECT_IMG_KEY = "img"
